// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Naive_bayesML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("categoria"), LoadColumn(1)]
        public string Categoria { get; set; }


        [ColumnName("comentario"), LoadColumn(2)]
        public string Comentario { get; set; }


    }
}
